### ISSUE TITLE
New alters (not in predefined list) not allowed

### ISSUE THREAD

**Issue by PEvelynNguyen** [qualintitative/egoweb#11]
Hello,

I have a predefined participant list (under Study settings). The "Restrict alters to participant list" is NOT CHECKED. However, when I tried to enter a name that is not in this list, it said "Name not found in list".

Do you know how to fix this problem?

Thanks a lot,
Evelyn

**Comment by qualintitative** [comment]
Hmmmm....I'll have to test this myself to recreate the problem.

**Comment by qualintitative** [comment]
I recreated the problem on my end.  I added it to @zhangster list to look into.  Hope it is a quick fix.

**Comment by qualintitative** [comment]
Sorry this is definitely a new problem for a feature that has worked in the past.  It is not a well used feature so far so it is hard to know what broke it or when.  I'm waiting for David to get back to me.  He seems busy at the moment.

**Comment by qualintitative** [comment]
@PEvelynNguyen the dev branch has a fix for this problem now.  I just tested it and it seemed to work.

**Comment by qualintitative** [comment]
I'm going to ask @zhangster to merge this change with the master branch unless he thinks there might be a problem with doing that.

**Comment by qualintitative** [comment]
I think the merge happened, so now master should work for this.

**Comment by PEvelynNguyen** [comment]
Thanks a lot, David. I'll test it now.

**Comment by PEvelynNguyen** [comment]
Confirm it works. Thank you!
