### ISSUE TITLE
arrow keys not functional in textual_pp response boxes

### ISSUE THREAD

**Issue by qualintitative** [qualintitative/egoweb#26]
When typing a response in a Textual_pp box it is necessary to use the arrow keys just like any other text box (for example this one) so that respondents / interviewers can easily edit responses.  This is currently not functioning in dev.

**Comment by zhangster** [comment]
this should be fixed with the recent updates

**Comment by qualintitative** [comment]
I'm checking on different browsers / devices but this worked on chrome / iphone

**Comment by qualintitative** [comment]
This is fixed.
